version: '3'
services:
  elastic:
    image: blacktop/elasticsearch
    ports:
    - "10200:9200"

  mongo:
    image: mvertes/alpine-mongo

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"